---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custms
  template:
    metadata:
      labels:
        app: custms
    spec:
      imagePullSecrets:
      - name: karthi03
      containers:
      - name: custms-container
        image: democustomermsacr.azurecr.io/democustms:latest
        imagePullPolicy: Always
        env:
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: custms